package com.victor.calendar.util

const val BASE_URL =
    "https://holidays.abstractapi.com/"
const val MILLIS_IN_SECOND: Long = 1000L
const val MILLIS_IN_MINUTE: Long = 60 * MILLIS_IN_SECOND
const val MILLIS_IN_HOUR: Long = 60 * MILLIS_IN_MINUTE
const val MILLIS_IN_DAY: Long = 24 * MILLIS_IN_HOUR
const val MILLIS_IN_WEEK: Long = 7 * MILLIS_IN_DAY

const val API_KEY = "40e982d26d564382bda75354a1427dbd"

val countriesMap = mapOf(
    "AFGHANISTAN" to "AF",
    "ALBANIA" to "AL",
    "ALGERIA" to "DZ",
    "ANDORRA" to "AD",
    "ANGOLA" to "AO",
    "ANTIGUA AND BARBUDA" to "AG",
    "ARGENTINA" to "AR",
    "ARMENIA" to "AM",
    "AUSTRALIA" to "AU",
    "AUSTRIA" to "AT",
    "AZERBAIJAN" to "AZ",
    "BAHAMAS" to "BS",
    "BAHRAIN" to "BH",
    "BANGLADESH" to "BD",
    "BARBADOS" to "BB",
    "BELARUS" to "BY",
    "BELGIUM" to "BE",
    "BELIZE" to "BZ",
    "BENIN" to "BJ",
    "BHUTAN" to "BT",
    "BOLIVIA (PLURINATIONAL STATE OF)" to "BO",
    "BOSNIA AND HERZEGOVINA" to "BA",
    "BOTSWANA" to "BW",
    "BRAZIL" to "BR",
    "BRUNEI DARUSSALAM" to "BN",
    "BULGARIA" to "BG",
    "BURKINA FASO" to "BF",
    "BURUNDI" to "BI",
    "CABO VERDE" to "CV",
    "CAMBODIA" to "KH",
    "CAMEROON" to "CM",
    "CANADA" to "CA",
    "CENTRAL AFRICAN REPUBLIC" to "CF",
    "CHAD" to "TD",
    "CHILE" to "CL",
    "CHINA" to "CN",
    "COLOMBIA" to "CO",
    "COMOROS" to "KM",
    "CONGO" to "CG",
    "CONGO, DEMOCRATIC REPUBLIC OF THE" to "CD",
    "COSTA RICA" to "CR",
    "CÔTE D'IVOIRE" to "CI",
    "CROATIA" to "HR",
    "CUBA" to "CU",
    "CYPRUS" to "CY",
    "CZECHIA" to "CZ",
    "DENMARK" to "DK",
    "DJIBOUTI" to "DJ",
    "DOMINICA" to "DM",
    "DOMINICAN REPUBLIC" to "DO",
    "ECUADOR" to "EC",
    "EGYPT" to "EG",
    "EL SALVADOR" to "SV",
    "EQUATORIAL GUINEA" to "GQ",
    "ERITREA" to "ER",
    "ESTONIA" to "EE",
    "ESWATINI" to "SZ",
    "ETHIOPIA" to "ET",
    "FIJI" to "FJ",
    "FINLAND" to "FI",
    "FRANCE" to "FR",
    "GABON" to "GA",
    "GAMBIA" to "GM",
    "GEORGIA" to "GE",
    "GERMANY" to "DE",
    "GHANA" to "GH",
    "GREECE" to "GR",
    "GRENADA" to "GD",
    "GUATEMALA" to "GT",
    "GUINEA" to "GN",
    "GUINEA-BISSAU" to "GW",
    "GUYANA" to "GY",
    "HAITI" to "HT",
    "HONDURAS" to "HN",
    "HUNGARY" to "HU",
    "ICELAND" to "IS",
    "INDIA" to "IN",
    "INDONESIA" to "ID",
    "IRAN (ISLAMIC REPUBLIC OF)" to "IR",
    "IRAQ" to "IQ",
    "IRELAND" to "IE",
    "ISRAEL" to "IL",
    "ITALY" to "IT",
    "JAMAICA" to "JM",
    "JAPAN" to "JP",
    "JORDAN" to "JO",
    "KAZAKHSTAN" to "KZ",
    "KENYA" to "KE",
    "KIRIBATI" to "KI",
    "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)" to "KP",
    "KOREA, REPUBLIC OF" to "KR",
    "KUWAIT" to "KW",
    "KYRGYZSTAN" to "KG",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC" to "LA",
    "LATVIA" to "LV",
    "LEBANON" to "LB",
    "LESOTHO" to "LS",
    "LIBERIA" to "LR",
    "LIBYA" to "LY",
    "LIECHTENSTEIN" to "LI",
    "LITHUANIA" to "LT",
    "LUXEMBOURG" to "LU",
    "MADAGASCAR" to "MG",
    "MALAWI" to "MW",
    "MALAYSIA" to "MY",
    "MALDIVES" to "MV",
    "MALI" to "ML",
    "MALTA" to "MT",
    "MARSHALL ISLANDS" to "MH",
    "MAURITANIA" to "MR",
    "MAURITIUS" to "MU",
    "MEXICO" to "MX",
    "MICRONESIA (FEDERATED STATES OF)" to "FM",
    "MOLDOVA, REPUBLIC OF" to "MD",
    "MONACO" to "MC",
    "MONGOLIA" to "MN",
    "MONTENEGRO" to "ME",
    "MOROCCO" to "MA",
    "MOZAMBIQUE" to "MZ",
    "MYANMAR" to "MM",
    "NAMIBIA" to "NA",
    "NAURU" to "NR",
    "NEPAL" to "NP",
    "NETHERLANDS" to "NL",
    "NEW ZEALAND" to "NZ",
    "NICARAGUA" to "NI",
    "NIGER" to "NE",
    "NIGERIA" to "NG",
    "NORTH MACEDONIA" to "MK",
    "NORWAY" to "NO",
    "OMAN" to "OM",
    "PAKISTAN" to "PK",
    "PALAU" to "PW",
    "PANAMA" to "PA",
    "PAPUA NEW GUINEA" to "PG",
    "PARAGUAY" to "PY",
    "PERU" to "PE",
    "PHILIPPINES" to "PH",
    "POLAND" to "PL",
    "PORTUGAL" to "PT",
    "QATAR" to "QA",
    "ROMANIA" to "RO",
    "RUSSIAN FEDERATION" to "RU",
    "RWANDA" to "RW",
    "SAINT KITTS AND NEVIS" to "KN",
    "SAINT LUCIA" to "LC",
    "SAINT VINCENT AND THE GRENADINES" to "VC",
    "SAMOA" to "WS",
    "SAN MARINO" to "SM",
    "SAO TOME AND PRINCIPE" to "ST",
    "SAUDI ARABIA" to "SA",
    "SENEGAL" to "SN",
    "SERBIA" to "RS",
    "SEYCHELLES" to "SC",
    "SIERRA LEONE" to "SL",
    "SINGAPORE" to "SG",
    "SLOVAKIA" to "SK",
    "SLOVENIA" to "SI",
    "SOLOMON ISLANDS" to "SB",
    "SOMALIA" to "SO",
    "SOUTH AFRICA" to "ZA",
    "SOUTH SUDAN" to "SS",
    "SPAIN" to "ES",
    "SRI LANKA" to "LK",
    "SUDAN" to "SD",
    "SURINAME" to "SR",
    "SWEDEN" to "SE",
    "SWITZERLAND" to "CH",
    "SYRIAN ARAB REPUBLIC" to "SY",
    "TAJIKISTAN" to "TJ",
    "TANZANIA, UNITED REPUBLIC OF" to "TZ",
    "THAILAND" to "TH",
    "TIMOR-LESTE" to "TL",
    "TOGO" to "TG",
    "TONGA" to "TO",
    "TRINIDAD AND TOBAGO" to "TT",
    "TUNISIA" to "TN",
    "TURKEY" to "TR",
    "TURKMENISTAN" to "TM",
    "TUVALU" to "TV",
    "UGANDA" to "UG",
    "UKRAINE" to "UA",
    "UNITED ARAB EMIRATES" to "AE",
    "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND" to "GB",
    "UNITED STATES OF AMERICA" to "US",
    "URUGUAY" to "UY",
    "UZBEKISTAN" to "UZ",
    "VANUATU" to "VU",
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)" to "VE",
    "VIET NAM" to "VN",
    "YEMEN" to "YE",
    "ZAMBIA" to "ZM",
    "ZIMBABWE" to "ZW"
)

val countriesMapList = countriesMap.keys.toList()




